# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
    - name: Test with pytest
      run: |
        pytest --cov=myapp --cov-fail-under=70 --cov-report=html
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/index.html

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        echo Build completed

  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Replace badge
        id: check_badge
        run: |
          BADGE_LINE="![Build Status](https://github.com/${{ github.repository }}/actions/workflows/${{ github.workflow }}/badge.svg?branch=develop)"

          if grep -q '!\[Build Status\](https://github.com/.*/actions/workflows/.*badge.svg.*)' README.md; then
            echo "Updating existing badge..."
            sed -i 's|!\[Build Status\](https://github.com/.*/actions/workflows/.*badge.svg.*)|'"$BADGE_LINE"'|g' README.md
          else
            echo "Adding new badge..."
            echo -e "\n$BADGE_LINE\n" >> README.md
          fi

      - name: Commit and push changes to PR branch
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add README.md
          git commit -m "Add CI badge to README"
          git push origin HEAD:${{ github.head_ref }}        
